substitutions:
  _REGION: "us-central1"
  _REPOSITORY: "repoai-ai"
  _IMAGE: "repoai-ai"
  _SERVICE: "repoai-service"
  _PROJECT_ID: "gen-lang-client-0265539996"
  _GEMINI_MODEL: "gemini-2.0-flash-exp"
  _GEMINI_DEFAULT_TIMEOUT_S: "60"
  _GEMINI_MAX_RETRIES: "2"
  _EMBEDDING_MODEL: "text-embedding-004"
  _MODEL_ROUTE_ORCHESTRATOR: "gemini-2.5-flash,gemini-2.0-flash-exp,gemini-2.0-flash"
  _MODEL_ROUTE_INTAKE: "gemini-2.5-flash,gemini-2.0-flash-exp,gemini-2.0-flash"
  _MODEL_ROUTE_PLANNER: "gemini-2.5-pro,gemini-2.5-flash,gemini-2.0-flash"
  _MODEL_ROUTE_CODER: "gemini-2.5-pro,gemini-2.5-flash,gemini-2.0-flash"
  _MODEL_ROUTE_PR: "gemini-2.5-flash,gemini-2.0-flash,gemini-2.5-flash-lite"

options:
  # Use CLOUD_LOGGING_ONLY when using a custom service account to avoid
  # Cloud Build rejecting the request for missing logs bucket configuration.
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    # Build from the `repoai-ai` subdirectory where the Dockerfile lives
    args: ["build", "-t", "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA", "repoai-ai"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
        # Deploy to Cloud Run
        # NOTE: Securely map secrets from Secret Manager into Cloud Run using
        # `--set-secrets ENV_VAR=SECRET_NAME:version`. Create secrets in Secret Manager
        # first and grant the Cloud Build service account access to them.
        # Example: --set-secrets DB_PASSWORD=DB_PASSWORD:latest,API_KEY=API_KEY:latest
        gcloud run deploy $_SERVICE \
          --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA \
          --region=$_REGION \
          --platform=managed \
          --allow-unauthenticated \
          # Pass non-secret configuration from .env as environment variables
          --set-env-vars PORT=8000,GEMINI_MODEL="$_GEMINI_MODEL",GEMINI_DEFAULT_TIMEOUT_S="$_GEMINI_DEFAULT_TIMEOUT_S",GEMINI_MAX_RETRIES="$_GEMINI_MAX_RETRIES",EMBEDDING_MODEL="$_EMBEDDING_MODEL",MODEL_ROUTE_ORCHESTRATOR="$_MODEL_ROUTE_ORCHESTRATOR",MODEL_ROUTE_INTAKE="$_MODEL_ROUTE_INTAKE",MODEL_ROUTE_PLANNER="$_MODEL_ROUTE_PLANNER",MODEL_ROUTE_CODER="$_MODEL_ROUTE_CODER",MODEL_ROUTE_PR="$_MODEL_ROUTE_PR" \
          # Map sensitive values to Secret Manager entries (create these secrets first)
          --set-secrets GOOGLE_API_KEY=GOOGLE_API_KEY:latest

images:
  - "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA"

timeout: "1200s"
