substitutions:
  _REGION: "us-central1"
  _REPOSITORY: "repoai-ai"
  _IMAGE: "repoai-ai"
  _SERVICE: "repoai-service"
  _PROJECT_ID: "gen-lang-client-0265539996"
  _GEMINI_MODEL: "gemini-2.0-flash-exp"
  _GEMINI_DEFAULT_TIMEOUT_S: "60"
  _GEMINI_MAX_RETRIES: "2"
  _EMBEDDING_MODEL: "text-embedding-004"
  # Model route lists (commas allowed) — we'll write these into an env file
  # at build time and deploy using `--env-vars-file` to avoid CLI parsing issues.
  _MODEL_ROUTE_ORCHESTRATOR: "gemini-2.5-flash,gemini-2.0-flash-exp,gemini-2.0-flash"
  _MODEL_ROUTE_INTAKE: "gemini-2.5-flash,gemini-2.0-flash-exp,gemini-2.0-flash"
  _MODEL_ROUTE_PLANNER: "gemini-2.5-pro,gemini-2.5-flash,gemini-2.0-flash"
  _MODEL_ROUTE_CODER: "gemini-2.5-pro,gemini-2.5-flash,gemini-2.0-flash"
  _MODEL_ROUTE_PR: "gemini-2.5-flash,gemini-2.0-flash,gemini-2.5-flash-lite"

availableSecrets:
  secretManager:
    - versionName: "projects/gen-lang-client-0265539996/secrets/GOOGLE_API_KEY/versions/latest"
      env: "GOOGLE_API_KEY"

options:
  # Use CLOUD_LOGGING_ONLY when using a custom service account to avoid
  # Cloud Build rejecting the request for missing logs bucket configuration.
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    # Build from the `repoai-ai` subdirectory where the Dockerfile lives
    args: ["build", "-t", "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA", "repoai-ai"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    secretEnv: ["GOOGLE_API_KEY"]
    args:
      - -c
      - |
        # Create env.yaml with secret-injected GOOGLE_API_KEY and other vars
        cat > env.yaml <<EOF
        GOOGLE_API_KEY: "$${GOOGLE_API_KEY}"
        GEMINI_MODEL: "$_GEMINI_MODEL"
        GEMINI_DEFAULT_TIMEOUT_S: "$_GEMINI_DEFAULT_TIMEOUT_S"
        GEMINI_MAX_RETRIES: "$_GEMINI_MAX_RETRIES"
        EMBEDDING_MODEL: "$_EMBEDDING_MODEL"
        MODEL_ROUTE_ORCHESTRATOR: "$_MODEL_ROUTE_ORCHESTRATOR"
        MODEL_ROUTE_INTAKE: "$_MODEL_ROUTE_INTAKE"
        MODEL_ROUTE_PLANNER: "$_MODEL_ROUTE_PLANNER"
        MODEL_ROUTE_CODER: "$_MODEL_ROUTE_CODER"
        MODEL_ROUTE_PR: "$_MODEL_ROUTE_PR"
        EOF

        # Deploy using env-vars-file to avoid CLI comma-parsing issues
        gcloud run deploy $_SERVICE \
          --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA \
          --region=$_REGION \
          --platform=managed \
          --allow-unauthenticated \
          --env-vars-file=env.yaml

images:
  - "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA"

timeout: "1200s"
