substitutions:
  _REGION: us-central1
  _SERVICE: repoai-backend
  _REPO: repo-ai-backend
  _DB_NAME: repoai
  _CLOUDSQL: softwarecontinuous6731503060:us-central1:repoai

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud --quiet services enable \
          run.googleapis.com \
          artifactregistry.googleapis.com \
          cloudbuild.googleapis.com \
          secretmanager.googleapis.com \
          sqladmin.googleapis.com

  # Ensure Docker can push to Artifact Registry
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker $_REGION-docker.pkg.dev -q

  # Build image from the backend folder (Dockerfile and context are here)
  - name: gcr.io/cloud-builders/docker
    dir: repoai-backend
    args:
      - build
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud --quiet run deploy $_SERVICE \
          --region=$_REGION \
          --image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA \
          --platform=managed \
          --allow-unauthenticated \
          --add-cloudsql-instances=$_CLOUDSQL \
          --set-env-vars="APP_FRONTEND_URL=https://your-frontend-url,DB_URL=jdbc:mysql:///$_DB_NAME?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=$_CLOUDSQL&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC,DB_USERNAME=repoai" \
          --set-secrets="DB_PASSWORD=DB_PASSWORD:latest,GITHUB_CLIENT_ID=GITHUB_CLIENT_ID:latest,GITHUB_CLIENT_SECRET=GITHUB_CLIENT_SECRET:latest"

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA