steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
  
  # Build the React app
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
  
  # Deploy to Cloud Storage or Cloud Run (choose one)
  
  # Option 1: Deploy to Cloud Storage (static hosting)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', './dist', 'gs://${_BUCKET_NAME}']
  
  # Set proper cache headers
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['setmeta', '-h', 'Cache-Control:public,max-age=3600', '-r', 'gs://${_BUCKET_NAME}']

# Substitutions for bucket name
substitutions:
  _BUCKET_NAME: 'repo-ai'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'