# Clean Cloud Build config for building a React/Vite project and deploying to GCS

steps:
  # 1) Ensure bucket exists
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "Checking for bucket: gs://${_BUCKET_NAME}"
        if ! gsutil ls -b "gs://${_BUCKET_NAME}" >/dev/null 2>&1; then
          echo "Bucket gs://${_BUCKET_NAME} not found. Creating..."
          gsutil mb -p "$PROJECT_ID" -l "${_BUCKET_LOCATION}" "gs://${_BUCKET_NAME}"
          echo "Created bucket gs://${_BUCKET_NAME}"
        else
          echo "Bucket exists: gs://${_BUCKET_NAME}"
        fi

  # 2) Install dependencies
  - name: 'node:20'
    dir: 'repoai-frontend'
    entrypoint: npm
    args: ['install']

  # 3) Build the React app
  - name: 'node:20'
    dir: 'repoai-frontend'
    entrypoint: npm
    args: ['run', 'build']

  # 4) Deploy to GCS via rsync
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'repoai-frontend'
    args: ['-m', 'rsync', '-r', '-c', '-d', './dist', 'gs://${_BUCKET_NAME}']

  # 5) Set cache headers for browser performance
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['setmeta', '-h', 'Cache-Control:public,max-age=3600', '-r', 'gs://${_BUCKET_NAME}']

substitutions:
  _BUCKET_NAME: "repo-ai"        # ← replace with your bucket name if needed
  _BUCKET_LOCATION: "us-central1" # region for bucket creation

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
