# Clean Cloud Build config for building a React/Vite project and deploying to GCS

steps:
  # 1) Ensure bucket exists
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "Checking for bucket: gs://${_BUCKET_NAME}"
        if ! gsutil ls -b "gs://${_BUCKET_NAME}" >/dev/null 2>&1; then
          echo "Bucket gs://${_BUCKET_NAME} not found. Creating..."
          gsutil mb -p "$PROJECT_ID" -l "${_BUCKET_LOCATION}" "gs://${_BUCKET_NAME}"
          echo "Created bucket gs://${_BUCKET_NAME}"
        else
          echo "Bucket exists: gs://${_BUCKET_NAME}"
        fi

  # 2) Install dependencies
  - name: 'node:20'
    dir: 'repoai-frontend'
    entrypoint: npm
    args: ['install']

  # 3) Build the React app
  - name: 'node:20'
    dir: 'repoai-frontend'
    entrypoint: npm
    args: ['run', 'build']

  # Optional 4) Build container image and deploy to Cloud Run
  # Builds the Dockerfile located in repoai-frontend/, pushes to Container Registry,
  # then deploys to Cloud Run. Set `_CLOUD_RUN_SERVICE` and `_CLOUD_RUN_REGION` as substitutions.
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'repoai-frontend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE:-repoai-frontend}:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'repoai-frontend'
    args: ['push', 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE:-repoai-frontend}:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        SERVICE=${_CLOUD_RUN_SERVICE:-repoai-frontend}
        REGION=${_CLOUD_RUN_REGION:-us-central1}
        echo "Deploying image to Cloud Run: gcr.io/$PROJECT_ID/${SERVICE}:$SHORT_SHA"
        gcloud run deploy "$SERVICE" \
          --image "gcr.io/$PROJECT_ID/${SERVICE}:$SHORT_SHA" \
          --region "$REGION" \
          --platform managed \
          --allow-unauthenticated

  # 4) Deploy to GCS via rsync
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'repoai-frontend'
    args: ['-m', 'rsync', '-r', '-c', '-d', './dist', 'gs://${_BUCKET_NAME}']

  # 5) Set cache headers for browser performance
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['setmeta', '-h', 'Cache-Control:public,max-age=3600', '-r', 'gs://${_BUCKET_NAME}']

substitutions:
  _BUCKET_NAME: "repo-ai"        # ← replace with your bucket name if needed
  _BUCKET_LOCATION: "us-central1" # region for bucket creation
  # Cloud Run deployment substitutions
  _CLOUD_RUN_SERVICE: "repoai-frontend"
  _CLOUD_RUN_REGION: "us-central1"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
